### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by Edit-Mr** [rohanp/QuantumTicTacToe#8]
Can't open the website ):

**Comment by rohanp** [comment]
It seems heroku stopped offering a free tier for their servers, which is where this app was running. if you know of somewhere else I can host this app for free, please let me know

**Comment by Edit-Mr** [comment]
I'm a student so I got some heroku credit. I can host it if you wanted to😊
If it's a static website than host it on Github pages should work too.

Rohan Pandit ***@***.***> 於 2022年12月1日 週四 11:54 寫道：

**Comment by Edit-Mr** [comment]
@rohanp Okay I’ve deployed one on my heroku
https://quantum-ttt.herokuapp.com/

**Comment by rohanp** [comment]
Thank you! I'll update the link to point to yours
